 -- test04.module
 
 local modname = ...
 local M = {}
 _G[modname] = M
 package.loaded[modname] = M
 
 
 
 --[[
 ###############################################################################
 ###                              SETTINGS                                   ###
 ###############################################################################
 --]]
 
 local settings_table = {
 	{	
 		sizeX	= 100,
 		sizeY	= 100;
 		radius	= 20,
 	},
 }
 		
 --[[
 ###############################################################################
 ###                           END OF SETTINGS                               ###
 ###############################################################################
 --]]
 
 
 
 
 function M.test(t)
 	local color = { 0xff0000, 0x00ff00, 0x0000ff }
 	for x=1, 3
 	do
 		one4all_cairo.draw_box(cr, x*100, 20, t.sizeX, t.sizeY, t.radius, color[x], 0.5)
 	end
 end
 
 
 
 --[[
 ###############################################################################
 ###                            MODULE MAIN LOOP                             ###
 ###############################################################################
 --]]
 function M.main()
         for i in pairs(settings_table) do
             M.test(settings_table[i])
         end
 end
 
